name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: false
    default: 'World'
  num:
    description: 'Enter a number'
    required: false
    default: "1"
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
  num-squared:
    description: 'Square of the input'
    # need to specify the extra `value` field for `composite` actions
    value: ${{ steps.get-square.outputs.num-squared }}
runs:
  using: "composite"
  steps:
    # - uses: actions/checkout@v4
    - name: Set Greeting
      run: echo "Hello $INPUT_WHO_TO_GREET."
      shell: bash
      env:
        INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}

    - name: Random Number Generator
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash

    - name: Run scripts
      working-directory: ${{ github.action_path }}
      run: |
        ls -la
        src/goodbye.sh
      shell: bash

    - name: Pass Inputs to Shell
      run: |
          echo "INPUT_NUM=${{ inputs.num }}" >> $GITHUB_ENV
      shell: bash

    - name: Fetch the number's square
      id: get-square
      working-directory: ${{ github.action_path }}
      run: python src/get_square.py
      shell: bash