on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: test composite action
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: run local composite action
        id: foo
        uses: ./
        with:
          who-to-greet: 'Mona the Octocat'
          num: 7
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
      - run: echo num squared "$NUM_SQUARED"
        shell: bash
        env:
          NUM_SQUARED: ${{ steps.foo.outputs.num-squared }}